name: Conditional

on:
  repository_dispatch:
    types: Conditional

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Failed
      run: exit 1
      continue-on-error: true
    
    - name: On success
      if: success()
      run:  echo "SUCCESS"
    
    - name: On failure
      if: failure()
      run: echo "FAILURE"
