name: Build Nightly

on:
  repository_dispatch:
  push:
    types: build-nightly
  schedule:
    - cron:  '*/60 * * * *'

jobs:
  build:
    name: Run nightly build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'master'
      
      - name: Checkout master
      - run: git checkout master
        
      
