name: Do Something That Needs Scheduled

on:
  repository_dispatch:
  push:
    types: do-something
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: windows-latest
    steps:

      - name: Do Something
        run: echo Doing Something...
